all:
	gcc -o createkn01 createkn01.c -lm
	gcc -o bruteforce bruteforce.c -lm
	gcc -o backtrack backtrack.c -lm
	gcc -o dynpro dynpro.c -lm

clean:
	rm -f *.o createkn01
	rm -f *.o bruteforce
	rm -f *.o dynpro
	rm -f *.o backtrack
